# Week 2: NumPy Introduction for COMP 6721


In [2]:
import numpy as np

## 1. Basic Array Operations

In [3]:
# Creating NumPy arrays using np.array()
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Array attributes
print("Shape of arr1:", arr1.shape)  # Shape of arr1
print("Shape of arr2:", arr2.shape)  # Shape of arr2
print("Size of arr1:", arr1.size)    # Size of arr1
print("Size of arr2:", arr2.size)    # Size of arr2
print("Number of dimensions of arr1:", arr1.ndim)  # Number of dimensions of arr1
print("Number of dimensions of arr2:", arr2.ndim)  # Number of dimensions of arr2
print("Data type of arr1 elements:", arr1.dtype)   # Data type of arr1 elements
print("Data type of arr2 elements:", arr2.dtype)   # Data type of arr2 elements

Shape of arr1: (5,)
Shape of arr2: (2, 3)
Size of arr1: 5
Size of arr2: 6
Number of dimensions of arr1: 1
Number of dimensions of arr2: 2
Data type of arr1 elements: int64
Data type of arr2 elements: int64


In [4]:
# Array indexing and slicing
print("Element at index 0 of arr1:", arr1[0])            # Accessing single element
print("First row of arr2:", arr2[0][0])                     # Accessing single row
print("Element at row 1, column 2 of arr2:", arr2[1, 2]) # Accessing single element
print("Slicing arr1 from index 1 to 3:", arr1[1:4])       # Slicing array

Element at index 0 of arr1: 1
First row of arr2: 1
Element at row 1, column 2 of arr2: 6
Slicing arr1 from index 1 to 3: [2 3 4]


In [5]:

# Array manipulation
arr3 = np.arange(1, 10)        # Generate array with values from 1 to 9
arr4 = arr3.reshape(3, 3)      # Reshape arr3 into a 3x3 array
arr5 = np.hstack((arr4, arr4)) # Horizontally stack arr4 with itself
arr6 = np.vstack((arr4, arr4)) # Vertically stack arr4 with itself

print("Original array (arr3):", arr3)
print("Reshaped array (arr4):\n", arr4)
print("Horizontally stacked array (arr5):\n", arr5)
print("Vertically stacked array (arr6):\n", arr6)

Original array (arr3): [1 2 3 4 5 6 7 8 9]
Reshaped array (arr4):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Horizontally stacked array (arr5):
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
Vertically stacked array (arr6):
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


## 2. Array Initialization

In [6]:
# Generating arrays with predetermined values
zeros_array = np.zeros((2, 3))       # 2x3 array filled with zeros
ones_array = np.ones((3, 2))         # 3x2 array filled with ones
custom_value_array = np.full((2, 2), 5)  # 2x2 array filled with custom value (5)

print("Array of zeros:\n", zeros_array)
print("Array of ones:\n", ones_array)
print("Array filled with custom value:\n", custom_value_array)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array filled with custom value:
 [[5 5]
 [5 5]]


In [7]:
# Creating arrays with a range of values
range_array = np.arange(1, 10, 2)   # Array with values from 1 to 9 with step 2
linspace_array = np.linspace(0, 1, 5)  # Array with 5 evenly spaced values between 0 and 1

print("Array generated with arange:\n", range_array)
print("Array generated with linspace:\n", linspace_array)


Array generated with arange:
 [1 3 5 7 9]
Array generated with linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [8]:
# Generating random arrays
random_array1 = np.random.rand(2, 2)   # 2x2 array of random floats between 0 and 1
random_array2 = np.random.randn(2, 2)  # 2x2 array of random floats from a standard normal distribution
random_array3 = np.random.randint(1, 10, size=(2, 2))  # 2x2 array of random integers between 1 and 10

print("Random array with random floats between 0 and 1:\n", random_array1)
print("Random array with random floats from standard normal distribution:\n", random_array2)
print("Random array with random integers between 1 and 10:\n", random_array3)

Random array with random floats between 0 and 1:
 [[0.21306748 0.16051734]
 [0.03594545 0.35788198]]
Random array with random floats from standard normal distribution:
 [[ 0.89357697  0.51244025]
 [-0.67497246 -0.8755104 ]]
Random array with random integers between 1 and 10:
 [[3 8]
 [8 9]]


## 3. Array Operations

In [9]:
# Create sample arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise operations
print("Element-wise addition:\n", arr1 + arr2)
print("Element-wise subtraction:\n", arr1 - arr2)
print("Element-wise multiplication:\n", arr1 * arr2)
print("Element-wise division:\n", arr1 / arr2)

Element-wise addition:
 [[ 6  8]
 [10 12]]
Element-wise subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Element-wise division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
# Broadcasting
scalar = 2
print("Scalar addition:\n", arr1 + scalar)
print("Scalar multiplication:\n", arr1 * scalar)

Scalar addition:
 [[3 4]
 [5 6]]
Scalar multiplication:
 [[2 4]
 [6 8]]


In [11]:
# Universal functions (ufuncs)
print("Square root of arr1:\n", np.sqrt(arr1))
print("Exponential function on arr2:\n", np.exp(arr2))
print("Natural logarithm of arr1:\n", np.log(arr1))

Square root of arr1:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Exponential function on arr2:
 [[ 148.4131591   403.42879349]
 [1096.63315843 2980.95798704]]
Natural logarithm of arr1:
 [[0.         0.69314718]
 [1.09861229 1.38629436]]


In [13]:
arr1

array([[1, 2],
       [3, 4]])

In [16]:
# Aggregation functions
print("Sum of all elements in arr1:", np.sum(arr1, 1))
print("Minimum value in arr2:", np.min(arr2, 1))
print("Maximum value in arr1:", np.max(arr1))
print("Mean of all elements in arr2:", np.mean(arr2))

Sum of all elements in arr1: [3 7]
Minimum value in arr2: [5 7]
Maximum value in arr1: 4
Mean of all elements in arr2: 6.5


## 4. Array Manipulation

In [19]:
# Creating a sample array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Transposing arrays
arr_transposed = np.transpose(arr)
print("Original array:\n", arr)
print("Transposed array:\n", arr_transposed)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
# Reshaping arrays
arr_reshaped = arr.reshape(1, 9)
print("Original array:\n", arr)
print("Reshaped array:\n", arr_reshaped)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array:
 [[1 2 3 4 5 6 7 8 9]]


In [21]:
# Concatenating arrays
arr_concatenated = np.concatenate((arr, arr), axis=1)  # Horizontal concatenation
print("Original array:\n", arr)
print("Concatenated array (horizontal):\n", arr_concatenated)

arr_concatenated_vertical = np.concatenate((arr, arr), axis=0)  # Vertical concatenation
print("Original array:\n", arr)
print("Concatenated array (vertical):\n", arr_concatenated_vertical)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Concatenated array (horizontal):
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Concatenated array (vertical):
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# Splitting arrays
arr_split = np.split(arr_concatenated, 2, axis=1)  # Split horizontally
print("Original array:\n", arr_concatenated)
print("Split arrays (horizontal):\n", arr_split)

Original array:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
Split arrays (horizontal):
 [array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]


In [34]:
arr_split[0], arr_split[1]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [23]:
# Flattening arrays
arr_flattened = arr.flatten()
print("Original array:\n", arr)
print("Flattened array:\n", arr_flattened)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array:
 [1 2 3 4 5 6 7 8 9]


## 5. Indexing and Slicing


In [35]:
# Creating a sample array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Basic indexing and slicing
print("Element at row 0, column 1:", arr[0, 1])
print("First row:", arr[0])
print("Last column:", arr[:, -1])
print("Subarray from row 1 to 2, column 1 to 2:\n", arr[1:3, 1:3])

Element at row 0, column 1: 2
First row: [1 2 3]
Last column: [3 6 9]
Subarray from row 1 to 2, column 1 to 2:
 [[5 6]
 [8 9]]


In [36]:
# Boolean indexing
mask = arr > 5
print(mask)
print("Elements greater than 5:", arr[mask])

[[False False False]
 [False False  True]
 [ True  True  True]]
Elements greater than 5: [6 7 8 9]


In [37]:
np.where(mask)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [38]:
# Fancy indexing
rows_to_select = [0, 2]
print("Selected rows using fancy indexing:\n", arr[rows_to_select])

Selected rows using fancy indexing:
 [[1 2 3]
 [7 8 9]]


## 6. Array Operations and Functions

In [39]:
# Create sample arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [40]:
# Linear algebra operations
dot_product = np.dot(arr1, arr2)  # Dot product
matrix_product = arr1 @ arr2      # Matrix multiplication

print("Dot product of arr1 and arr2:\n", dot_product)
print("Matrix multiplication of arr1 and arr2:\n", matrix_product)

Dot product of arr1 and arr2:
 [[19 22]
 [43 50]]
Matrix multiplication of arr1 and arr2:
 [[19 22]
 [43 50]]


In [41]:
# Statistical functions
print("Mean of arr1:", np.mean(arr1))
print("Median of arr2:", np.median(arr2))
print("Standard deviation of arr1:", np.std(arr1))
print("Sum of arr2:", np.sum(arr2))

Mean of arr1: 2.5
Median of arr2: 6.5
Standard deviation of arr1: 1.118033988749895
Sum of arr2: 26


In [42]:
# Trigonometric functions
print("Sine of arr1:\n", np.sin(arr1))
print("Cosine of arr2:\n", np.cos(arr2))

Sine of arr1:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
Cosine of arr2:
 [[ 0.28366219  0.96017029]
 [ 0.75390225 -0.14550003]]


In [43]:
# Sorting arrays
arr3 = np.array([3, 1, 2, 5, 4])
sorted_indices = np.argsort(arr3)  # Indices that would sort the array
sorted_arr = np.sort(arr3)          # Sorted array

print("Original array:", arr3)
print("Sorted indices:", sorted_indices)
print("Sorted array:", sorted_arr)

Original array: [3 1 2 5 4]
Sorted indices: [1 2 0 4 3]
Sorted array: [1 2 3 4 5]


## 7. Broadcasting

In [48]:
# Create sample arrays
arr1 = np.array([[1, 2], [3, 4]])
scalar = 2

In [45]:
# Broadcasting with a scalar
result_scalar_addition = arr1 + scalar
result_scalar_multiplication = arr1 * scalar

print("Original array:\n", arr1)
print("Array after scalar addition:\n", result_scalar_addition)
print("Array after scalar multiplication:\n", result_scalar_multiplication)

Original array:
 [[1 2]
 [3 4]]
Array after scalar addition:
 [[3 4]
 [5 6]]
Array after scalar multiplication:
 [[2 4]
 [6 8]]


In [46]:
# Broadcasting with arrays of different shapes
arr2 = np.array([5, 6])

result_broadcasting = arr1 + arr2

print("Original array:\n", arr1)
print("Array to broadcast with:\n", arr2)
print("Result after broadcasting:\n", result_broadcasting)

Original array:
 [[1 2]
 [3 4]]
Array to broadcast with:
 [5 6]
Result after broadcasting:
 [[ 6  8]
 [ 8 10]]


## 8. Additional Features

In [51]:
# Saving and loading arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save('my_array.npy', arr)  # Save array to a file
loaded_arr = np.load('my_array.npy')  # Load array from file

print("Original array:\n", arr)
print("Loaded array:\n", loaded_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Loaded array:
 [[1 2 3]
 [4 5 6]]


In [52]:
# Copying arrays: views vs copies
arr_copy = arr.copy()  # Create a deep copy of the array
arr_view = arr.view()  # Create a view of the array (shallow copy)

print("Original array:\n", arr)
print("Copied array:\n", arr_copy)
print("View of the array:\n", arr_view)

Original array:
 [[1 2 3]
 [4 5 6]]
Copied array:
 [[1 2 3]
 [4 5 6]]
View of the array:
 [[1 2 3]
 [4 5 6]]


In [53]:
# Handling missing data: masked arrays
masked_arr = np.ma.masked_array([1, 2, 3, -1, 5], mask=[0, 0, 0, 1, 0])  # Create a masked array
print("Original array:\n", masked_arr)
print("Masked elements:", masked_arr.mask)

Original array:
 [1 2 3 -- 5]
Masked elements: [False False False  True False]


<div style="border-bottom: 3px solid black;"></div>

### Exercise &ndash; Use Numpy to write vectorized code
Suppose you are given the function below, where _x_ is a two-dimensional ndarray of numbers. You can assume _x_ is not empty (has at least one item).

In [1]:
import numpy as np

In [2]:
def exercise_loop(x):
    n, m = x.shape
    v = x[0,0]
    for i in range(n):
        for j in range(m):
            if x[i,j] > v:
                v = x[i,j]

    y = np.empty_like(x)
    for i in range(n):
        for j in range(m):
            y[i,j] = x[i,j] - v

    return y

You should know Python and Numpy well enough to figure out what the above code does.

The below code uses Numpy in a way that doesn't require Python for-loops. In other words, your solution should be completely _vectorized_. This is similar to writing good Matlab code. Write your answer in the code cell below. Aim for 1 line of code.

In [3]:
def exercise_vectorized(x):
    return x - np.max(x)

In [4]:
assert 'exercise_loop' in globals(), "You forgot to run the code cell with the loop-based code!"
assert 'exercise_vectorized' in globals(), "You forgot to run the code cell with your answer!"
for i in range(10):
    x = np.random.randint(100, size=(5, 3))
    y = exercise_vectorized(x)
    y_correct = exercise_loop(x)
    assert isinstance(y, np.ndarray), "You didn't return an ndarray object!"
    assert y.shape == x.shape, "You returned an ndarray but of the wrong shape!"
    assert y.dtype == x.dtype, "You returned an ndarray but of the wrong dtype!"
    assert np.array_equal(y, y_correct), "Wrong result!\nx:\n%s\nexpected:\n%s\nreturned:\n%s" % (x, y_correct, y)

import timeit
x = np.random.randint(1000, size=(200, 200))
loop_time = timeit.timeit('exercise_loop(x)',      setup="from __main__ import exercise_loop, x", number=10)
vec_time = timeit.timeit('exercise_vectorized(x)', setup="from __main__ import exercise_vectorized, x", number=10)
print("Our vectorized code ran %.1fx faster than the original code on a 200x200 matrix" % (loop_time/vec_time))

Our vectorized code ran 535.8x faster than the original code on a 200x200 matrix
