In [37]:
import numpy as np

In [38]:

def manhattan(points, centroids):
    distances = np.zeros((len(points), len(centroids)), dtype=float)
    for i, p in enumerate(points):
        px, py = p
        for j, c in enumerate(centroids):
            cx, cy = c
            distances[i, j] = abs(px-cx)+abs(py-cy)
            # print(f"P{i+1} C{j+1}", distances[i,j])
    # calculate new points
    points_c_index = np.argmin(distances, axis=1)
    new_centroids = np.zeros(centroids.shape)
    for j in range(len(centroids)):
        total = np.array([0 , 0])
        count = 0.0
        for i, p in enumerate(points_c_index):
            if p == j:
                total += points[i]
                count += 1
        total = total/count
        new_centroids[j] = total
    return distances, new_centroids


In [39]:
points = np.array([
    [1, 2],
    [2, 7],
    [3, 3],
    [6, 4],
    [7, 8],
    [8, 2],
    [9, 1],
])
centroids = np.array([
    [2, 7],
    [6, 4],
    [8, 2],
])


In [40]:
iteration = 0
new_centroids = centroids
while True:
    iteration += 1
    print(f"Iteration {iteration}")
    prev_centroids = new_centroids
    points_c_index, new_centroids = manhattan(points, prev_centroids)
    print(points_c_index)
    print(new_centroids)
    if np.all(prev_centroids == new_centroids):
        break


Iteration 1
[[ 6.  7.  7.]
 [ 0.  7. 11.]
 [ 5.  4.  6.]
 [ 7.  0.  4.]
 [ 6.  5.  7.]
 [11.  4.  0.]
 [13.  6.  2.]]
[[1.5        4.5       ]
 [5.33333333 5.        ]
 [8.5        1.5       ]]
Iteration 2
[[ 3.          7.33333333  8.        ]
 [ 3.          5.33333333 12.        ]
 [ 3.          4.33333333  7.        ]
 [ 5.          1.66666667  5.        ]
 [ 9.          4.66666667  8.        ]
 [ 9.          5.66666667  1.        ]
 [11.          7.66666667  1.        ]]
[[2.  4. ]
 [6.5 6. ]
 [8.5 1.5]]
Iteration 3
[[ 3.   9.5  8. ]
 [ 3.   5.5 12. ]
 [ 2.   6.5  7. ]
 [ 4.   2.5  5. ]
 [ 9.   2.5  8. ]
 [ 8.   5.5  1. ]
 [10.   7.5  1. ]]
[[2.  4. ]
 [6.5 6. ]
 [8.5 1.5]]
