In [1]:
import torch
import torch.nn.functional as F

In [2]:
# Input matrix
input = torch.tensor([[1, 0, 2, 1, 0],
                       [0, 1, 1, 0, 2],
                       [2, 0, 1, 2, 1],
                       [1, 1, 0, 1, 0],
                       [0, 2, 1, 0, 1]], dtype=torch.float32)

# Kernel
kernel = torch.tensor([[1, 0, -1],
                        [0, 1, 0],
                        [-1, 0, 1]], dtype=torch.float32)

# Reshape to (batch, channels, height, width)
input = input.unsqueeze(0).unsqueeze(0)
kernel = kernel.unsqueeze(0).unsqueeze(0)

# Apply convolution (stride=1, padding=0)
output = F.conv2d(input, kernel, stride=1, padding=0)
print(output)

tensor([[[[-1.,  2.,  2.],
          [-2.,  2.,  1.],
          [ 3., -4.,  1.]]]])


In [3]:
# Input matrix
input = torch.tensor([ [2, 1, 0, 1, 3],
                       [1, 0, 2, 1, 0],
                       [0, 3, 1, 0, 2],
                       [1, 0, 2, 3, 1],
                       [2, 1, 0, 1, 0]], dtype=torch.float32)

# Kernel
kernel = torch.tensor([ [0, 1, 0],
                        [1, 2, 1],
                        [0, 1, 0]], dtype=torch.float32)

# Reshape to (batch, channels, height, width)
input = input.unsqueeze(0).unsqueeze(0)
kernel = kernel.unsqueeze(0).unsqueeze(0)

# Apply convolution (stride=2, padding=1)
output = F.conv2d(input, kernel, stride=2, padding=1)
print(output)

tensor([[[[6., 4., 7.],
          [5., 9., 5.],
          [6., 4., 2.]]]])


In [4]:
# Input matrix
input = torch.tensor([ [1, 0, 1, 2, 0, 1, 0],
                       [0, 2, 1, 0, 1, 0, 2],
                       [1, 0, 3, 1, 2, 1, 0],
                       [2, 1, 0, 1, 0, 2, 1],
                       [0, 1, 2, 0, 3, 1, 0],
                       [1, 0, 1, 2, 1, 0, 1], 
                       [0, 2, 0, 1, 0, 1, 2]], dtype=torch.float32)

# Kernel
kernel = torch.tensor([ [1, 0, 1],
                        [0, -1, 0],
                        [1, 0, 1]], dtype=torch.float32)

# Reshape to (batch, channels, height, width)
input = input.unsqueeze(0).unsqueeze(0)
kernel = kernel.unsqueeze(0).unsqueeze(0)

# Apply convolution (stride=1, padding=0)
output = F.conv2d(input, kernel, stride=1, padding=0, dilation=2)
print(output)

tensor([[[[1., 2., 1.],
          [3., 1., 5.],
          [1., 4., 2.]]]])
